#!/bin/bash 

#VARIABLES
 
NOTIF="🌑 Dark mode is activated" 
DIR="$HOME/Images/wallpapers/dark"
PIC=$(ls $DIR/*|shuf -n1)

echo $NOTIF
notify-send -u normal -t 3000  $NOTIF

gsettings set org.gnome.desktop.background picture-uri file://$PIC 
gsettings set org.gnome.desktop.interface gtk-theme 'Dracula'
exit; 

